<?php

namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;
use Config\Database;

/**
 * db:export-schema — Phase S4: export a structure-only SQL baseline.
 *
 *   php spark db:export-schema             # writes db/baseline.sql
 *   php spark db:export-schema --out=/tmp/my.sql
 *
 * The baseline.sql is the prerequisite for Phase E1 (stripping runtime DDL
 * probes from model constructors and revoking ALTER from the web user).
 *
 * Outputs a CREATE TABLE skeleton derived from the live schema via CI4's
 * database introspection — no shell exec, no mysqldump binary required.
 * The generated SQL is compatible with MySQL 5.7+ and MariaDB 10.3+.
 *
 * Commit db/baseline.sql to version control so migrations can be validated
 * against a known-good schema state without a live DB.
 */
class DbExportSchema extends BaseCommand
{
    protected $group       = 'Database';
    protected $name        = 'db:export-schema';
    protected $description = 'Export the live schema (structure only) to db/baseline.sql (Phase S4).';
    protected $usage       = 'db:export-schema [--out=<path>]';

    public function run(array $params): int
    {
        $outPath = CLI::getOption('out') ?? ROOTPATH . 'db/baseline.sql';

        $outDir = dirname($outPath);
        if (! is_dir($outDir) && ! mkdir($outDir, 0755, true)) {
            CLI::error("Cannot create output directory: {$outDir}");
            return EXIT_ERROR;
        }

        $db     = Database::connect();
        $dbName = $db->getDatabase();

        CLI::write("Exporting schema from '{$dbName}' → {$outPath}", 'green');

        $tables = $db->listTables();
        if (empty($tables)) {
            CLI::error('No tables found — is the database empty?');
            return EXIT_ERROR;
        }

        $lines   = [];
        $lines[] = '-- isp-core schema baseline (structure only)';
        $lines[] = '-- Generated by: php spark db:export-schema';
        $lines[] = '-- Generated at: ' . date('Y-m-d H:i:s T');
        $lines[] = '-- Database:     ' . $dbName;
        $lines[] = '-- Tables:       ' . count($tables);
        $lines[] = '--';
        $lines[] = '-- This file is the S4 baseline — commit it so migrations can be';
        $lines[] = '-- validated against a known-good schema without a live DB.';
        $lines[] = '-- DO NOT include row data here; use backup.sh for full dumps.';
        $lines[] = '';
        $lines[] = 'SET FOREIGN_KEY_CHECKS = 0;';
        $lines[] = "USE `{$dbName}`;";
        $lines[] = '';

        $bar = CLI::getProgressBar();

        foreach ($tables as $i => $table) {
            $bar?->update($i / count($tables) * 100);

            // Fetch CREATE TABLE statement from MySQL (the authoritative shape).
            $row = $db->query("SHOW CREATE TABLE `{$table}`")->getRow();
            if ($row) {
                $createSql = is_object($row)
                    ? ($row->{'Create Table'} ?? $row->{'Create View'} ?? '')
                    : ($row['Create Table'] ?? $row['Create View'] ?? '');

                if ($createSql !== '') {
                    $lines[] = "-- Table: {$table}";
                    $lines[] = "DROP TABLE IF EXISTS `{$table}`;";
                    $lines[] = $createSql . ';';
                    $lines[] = '';
                }
            }
        }

        $lines[] = 'SET FOREIGN_KEY_CHECKS = 1;';
        $lines[] = '';

        if (file_put_contents($outPath, implode("\n", $lines)) === false) {
            CLI::error("Failed to write: {$outPath}");
            return EXIT_ERROR;
        }

        $size = round(filesize($outPath) / 1024, 1);
        CLI::write("Schema exported: {$outPath} ({$size} KB, " . count($tables) . ' tables)', 'green');
        CLI::write('Next step: review, then `git add db/baseline.sql && git commit`', 'yellow');

        return EXIT_SUCCESS;
    }
}
